//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuglBrennaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPost
    {
        public int ForumPostId { get; set; }
        public int ForumTopicId { get; set; }
        public int CreatedMemberId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ForumTopic ForumTopic { get; set; }
    }
}
