//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuglBrennaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RolePermissionId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> ForumSectionId { get; set; }
        public int Permission { get; set; }
    
        public virtual ForumSection ForumSection { get; set; }
        public virtual Role Role { get; set; }
    }
}
