//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuglBrennaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRealm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubRealm()
        {
            this.Events = new HashSet<Event>();
            this.Members = new HashSet<Member>();
        }
    
        public int SubRealmId { get; set; }
        public string SubRealmName { get; set; }
        public string SubRealmState { get; set; }
        public string SubRealmCity { get; set; }
        public string SubRealmAddress { get; set; }
        public string Location { get; set; }
        public string PracticeDay { get; set; }
        public string PracticeTime { get; set; }
        public int RealmId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        public virtual Realm Realm { get; set; }
    }
}
